export const CATEGORIES_ACTION_TYPES = {
    SET_CATEGORIES: "category/SET_CATEGORIES",
    FETCH_CATEGORIES_SUCCESS: "category/SET_CATEGORIES_SUCCESS",
    FETCH_CATEGORIES_FAILURE: "category/SET_CATEGORIES_FAILURE",
    FETCH_CATEGORIES_START: "category/SET_CATEGORIES_START",
}
